name: Publish NPM SDK

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC
  contents: read


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: actions/checkout@v6

      - name: test2
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
        
      - name: test3
        working-directory: bindings/javascript
        run: npm publish --access public --provenance
        env:
          NPM_CONFIG_PROVENANCE: true


